### ISSUE TITLE
how to integrate charm with dsvpn?

### ISSUE THREAD

**Issue by luckypoem** [jedisct1/charm#3]
can u give a detailed instruction?

**Comment by jedisct1** [comment]
`charm` is already included in `dsvpn`. This is what handles all the cryptographic operations.

**Comment by briteming** [comment]
hi.

here: https://github.com/jedisct1/dsvpn/issues/59 ,i ever said that i used dsvpn to try to cross the gfw(the great  firewall of china),but my vps ip was blocked for 2 times by the gfw.so i think charm is not a very strong encryption method. can u use some other encryption method such as industry-standard aes to encrypt the vpn connection?
 charm is really outdated.
